### ISSUE TITLE
Design and implement drag-drop puzzle event type

### ISSUE THREAD

**Issue by deSagaz** [deSagaz/java-sparrow#18]
With [Dragula](https://valor-software.com/ng2-dragula/index.html) we can create order-related puzzles. Now to design a good one.

**Comment by deSagaz** [comment]
This may be useful as well: https://shopify.github.io/draggable/

**Comment by ChaoticSymphony94** [comment]
I have found my entertainment  while in class, why is it so fun to drag those cubes around?!

**Comment by deSagaz** [comment]
I'll fix the scrolling issue

**Comment by deSagaz** [comment]
Bug with second time loading fixed as of b7220f98fea5eaa89e682625e82e9ec9a5a3cbc4
