### ISSUE TITLE
Gamified Student Model

### ISSUE THREAD

**Issue by deSagaz** [deSagaz/java-sparrow#20]

**Comment by deSagaz** [comment]
# Back-end requirements:
- [x] Add score model [User, Scene, Points]
    - [x] POST only (checks if within max. boundary of scene)
- [x] Add max. score and required score to scenes
    - [x] add to GET requests
- [x] Add total score to Story GET

# Front-end requirements:
- [x] Display scene scores from back-end (using user authentication)
- [x] Display story (total) scores from back-end (using user authentication)
- [x] Keep score inside sequences
- [x] Send scores to back-end at scene completion (using user authentication)

**Comment by Kelly-Griffioen** [comment]
I'm keeping score in the seq.ts page with this.score and I show it with 'ending()', but I barely know anything about the api so is "Send scores to back-end at scene completion" something I can quickly learn or is it better if I leave that to you?

**Comment by deSagaz** [comment]
You can do it, definitely, but the server side is not yet finished at the moment... I'd suggest pseudo-coding it with a `TODO` for now. Once implemented, it is basically about calling:

`this.api.post('/scene/finish/', { "score": 20 });`

Or something likewise, where the first parameter is the api url, and the second parameter is the object with any data the api needs.

**Comment by deSagaz** [comment]
*Well, and then you need to subscribe to it, yielding something like:*

```javascript
    this.api.get('/scene/finish/', params).subscribe(
      (response: object) => {
        // respond to successful call
      },
      (error: object) => {
        // respond to failed call
      }
    );
```

**Comment by deSagaz** [comment]
*(I've updated the requirements above)*
