### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by deSagaz** [deSagaz/java-sparrow#21]

**Comment by deSagaz** [comment]
Hint button is implemented. What shall we do with the feedback button idea, @Kelly-Griffioen ?
1. Double the hint button as feedback button and close the issue
2. Allow users to set a custom text (and perhaps colour) on the hint button through syntax
3. Implement a second button type (with e.g., different colour and text) for feedback - to allow both buttons to show at once

**Comment by Kelly-Griffioen** [comment]
Do we need to both show feedback and a hint at the same time? When I still used the placeholder I added 2 keys: hint and feedback (or maybe they were called different) and showed the hint during the question and the feedback when the answer was wrong. That allowed the teacher to add both, though maybe a bit limited. If we don't need to show them at the same time, we could just do something like that so we can use the same button.

**Comment by deSagaz** [comment]
That's possible, indeed. I don't think a scenario that both hint and feedback is required will be common.

Now that branching is implemented, adding a hint is simply done by adding `hint` to the `data` array. Perhaps for clarity, we can change the text of the button to `?`, so that it can be used for both. So, then both feedback and hints (and other optional texts) go via the `hint` array item, adding a multifunctional `?` button for the user.

Does that sound like a good idea?

**Comment by Kelly-Griffioen** [comment]
Yeah I think that's best. I noticed the doGeneric function takes care of showing the hint button so if we do it like this it gives the teacher a lot more options (if at some point turns out necessary) than just a hint or feedback.

**Comment by Kelly-Griffioen** [comment]
I changed the text of the button, so is there anything else that needs to be done for this button?

**Comment by deSagaz** [comment]
That's it 👍 Let's close this one!
