### ISSUE TITLE
Possible questions and answers for the Game

### ISSUE THREAD

**Issue by ChaoticSymphony94** [deSagaz/java-sparrow#22]

**Comment by ChaoticSymphony94** [comment]
2 multiple choices (talk with duck)

First question
What will the following code output to the console?
	
console.log(1 + “2” + “2”);	
console.log(“A” -  “B” + “2”);

answer 1: “122”, NAN (CORRECT)
Answer 2: 5, error
Answer 3: NaN, NaN
Answer 4: Nan, 2

Second Question

What is the output of the following? 

console.log( 1 < 2 < 3)
console.log( 5 < 3)

Answer 1: false, false
Answer 2: true, true
Answer 3: True , false (CORRECT)
Answer 4: false True

**Comment by ChaoticSymphony94** [comment]
1 mutliple choice question (alarm)

Which built in method adds one or more elements to the end of an array and returns the new length of the array? 

Answer 1: last()
Answer 2: put()
Answer 3: push() (CORRECT)
Answer 4: add()

**Comment by ChaoticSymphony94** [comment]
1 multiple chouce quesiotns (open door)

What is the correct JavaScript syntax to write “Exit Granted?

Answer 1: System.out.println(“Exit Granted”)
Answer 2: println(“Exit Granted”)
Answer 3: document.write(“Exit Granted”) (CORRECT)
Answer 4: response.write(“Exit Granted”)

**Comment by ChaoticSymphony94** [comment]
1 drag and drop question (lazer hall)
 
Move the lines of code in the correct order in order to disable the lazers
<html>
	<body>

		<script type= “text/javascript”>
			<!- - 
				Var lazer = true;
				Var alarm = false;
				Var  contact = false;
				If (lazer == true && contact == true) 
					{
						alarm = true;
}
				else 
					{
						lazer = false;
					}
			//-- >
		</script>
	</body>
<html>

**Comment by ChaoticSymphony94** [comment]
1 drag and drop question (elevator open)
Order the following code in the correct order to open the door.

var status = “closed”
var action = “open”
switch (action)
{
   case “lock”: 
   status = “locked”;
   break;
   
   case “open”: 
   status = “open”;
   break;
}

**Comment by ChaoticSymphony94** [comment]
Write in the code needed to slow the elevator:
var count = 100;
            
            document.write("Slowing descent";
            do{
               document.write("Currentspeed" + count);
               count--;
            }
            
            while (count > 0);
            document.write ("Elevator stopped");

**Comment by ChaoticSymphony94** [comment]
1 loop questions  (figth sequence)
For this fight complete the code for that every punch you avoid you hit them twice.
var punches;
var hits;
            document.write("Starting fighting");
         
            for(punches = 0; count < 5; count++){
               document.write("avoided" + punches + “ Punches”);
	       for(hits = 0; count < 2; count ++){
			
			document.write("landed " + punches + “ hits!”);
		}
            }

         
            document.write("Victory!");

**Comment by deSagaz** [comment]
Same as with #14 : can be directly uploaded to server now. Issue will close once finished.
