### ISSUE TITLE
Define and implement full stories API

### ISSUE THREAD

**Issue by deSagaz** [deSagaz/java-sparrow#5]

**Comment by Kelly-Griffioen** [comment]
g.com/api/auth POST for logging in
g.com/story/id/scene/id/seq/id
    story gets all stories /id gets one
    scene then gets all scenes from the specific story /id gets one
    same for sequence

**Comment by deSagaz** [comment]
@Ward-B , could you document the final api in the [wiki](https://github.com/deSagaz/java-sparrow/wiki) once finished? 😸

**Comment by deSagaz** [comment]
Split into separate issues now; will close.
